# version: '3'

# services:
#   docker_laravel:
#     image: php-docker-images:v1
#     ports:
#       - "8884:80"
#     environment:
#       - MYSQL_HOST=db-mariadb
#       - MYSQL_DATABASE=dbfaketwitter
#       - MYSQL_USERNAME=root
#       - MYSQL_ROOT_PASSWORD=root_password
#     container_name: php-docker-containter

# version: '3.8'
# services:
#   php-fpm:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/var/www/html
#     ports:
#       - "8884:8884"
#   nginx:
#     image: nginx:alpine
#     volumes:
#       - .:/var/www/html
#       - ./vhost.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "8080:8884"
#     depends_on:
#       - php-fpm


# version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - project_volume:/var/www/html
    ports:
      - "8884:8884"
  nginx:
    image: nginx:alpine
    volumes:
      - project_volume:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8884"
    depends_on:
      - php-fpm
  git:
    build:
      context: ./alpine
      dockerfile: Dockerfile
    volumes:
      - project_volume:/var/www/html
  # git:
  #   image: alpine/git
  #   # command: sh -c "while true; do sleep 3600; done"  # Command to keep the container running
  #   volumes:
  #     - project_volume:/var/www/html
volumes:
  project_volume:
